spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/users
  application:
    name: mongoweb
server:
  port: 8888

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: ERROR